/**
 * Mock Activities Data
 * Sample activity logs for timeline and activity feeds
 */
export const mockActivities = [
  {
    id: '1',
    type: 'story_completed',
    userId: '1',
    userName: 'John Doe',
    targetType: 'story',
    targetId: '1',
    targetName: 'User Registration',
    message: 'completed story "User Registration"',
    timestamp: '2024-11-10T14:30:00Z',
    projectId: '1',
  },
  {
    id: '2',
    type: 'task_created',
    userId: '1',
    userName: 'John Doe',
    targetType: 'task',
    targetId: '6',
    targetName: 'Implement OAuth callback handler',
    message: 'created task "Implement OAuth callback handler"',
    timestamp: '2024-11-18T09:15:00Z',
    projectId: '1',
  },
  {
    id: '3',
    type: 'sprint_started',
    userId: '2',
    userName: 'Jane Smith',
    targetType: 'sprint',
    targetId: '2',
    targetName: 'Sprint 2 - Authentication',
    message: 'started sprint "Sprint 2 - Authentication"',
    timestamp: '2024-11-18T08:00:00Z',
    projectId: '1',
  },
  {
    id: '4',
    type: 'task_assigned',
    userId: '2',
    userName: 'Jane Smith',
    targetType: 'task',
    targetId: '4',
    targetName: 'Create login API endpoint',
    message: 'assigned task to John Doe',
    timestamp: '2024-11-05T10:00:00Z',
    projectId: '1',
  },
  {
    id: '5',
    type: 'comment_added',
    userId: '3',
    userName: 'Mike Johnson',
    targetType: 'story',
    targetId: '6',
    targetName: 'Kanban Board',
    message: 'added a comment',
    timestamp: '2024-11-20T11:30:00Z',
    projectId: '1',
  },
  {
    id: '6',
    type: 'project_created',
    userId: '1',
    userName: 'John Doe',
    targetType: 'project',
    targetId: '1',
    targetName: 'AgileSAFe Platform',
    message: 'created project "AgileSAFe Platform"',
    timestamp: '2024-01-01T00:00:00Z',
    projectId: '1',
  },
]

