/**
 * Mock User Stories Data
 * Sample user stories with realistic data
 */
export const mockStories = [
  {
    id: '1',
    title: 'User Registration',
    description: 'As a new user, I want to register an account so I can access the platform',
    storyPoints: 5,
    priority: 'high',
    status: 'done',
    assignedTo: '1',
    featureId: 'auth',
    sprintId: '1',
    projectId: '1',
    acceptanceCriteria: [
      'User can register with email and password',
      'Email validation is implemented',
      'Password strength requirements are enforced',
    ],
    aiInsights: {
      complexity: 'medium',
      estimatedHours: 8,
      risk: 'low',
      recommendations: ['Consider adding social login options', 'Implement email verification'],
    },
    createdAt: '2024-11-01T00:00:00Z',
    updatedAt: '2024-11-10T00:00:00Z',
  },
  {
    id: '2',
    title: 'User Login',
    description: 'As a registered user, I want to login to access my account',
    storyPoints: 3,
    priority: 'high',
    status: 'done',
    assignedTo: '1',
    featureId: 'auth',
    sprintId: '1',
    projectId: '1',
    acceptanceCriteria: [
      'User can login with email and password',
      'Remember me functionality works',
      'Error messages are displayed for invalid credentials',
    ],
    aiInsights: {
      complexity: 'low',
      estimatedHours: 4,
      risk: 'low',
      recommendations: ['Add forgot password link', 'Implement rate limiting'],
    },
    createdAt: '2024-11-01T00:00:00Z',
    updatedAt: '2024-11-08T00:00:00Z',
  },
  {
    id: '3',
    title: 'Google OAuth Integration',
    description: 'As a user, I want to login with my Google account for convenience',
    storyPoints: 8,
    priority: 'medium',
    status: 'done',
    assignedTo: '1',
    featureId: 'auth',
    sprintId: '1',
    projectId: '1',
    acceptanceCriteria: [
      'User can login with Google account',
      'OAuth flow is secure',
      'User profile is synced from Google',
    ],
    aiInsights: {
      complexity: 'high',
      estimatedHours: 12,
      risk: 'medium',
      recommendations: ['Test OAuth flow thoroughly', 'Handle edge cases'],
    },
    createdAt: '2024-11-02T00:00:00Z',
    updatedAt: '2024-11-15T00:00:00Z',
  },
  {
    id: '4',
    title: 'Password Reset',
    description: 'As a user, I want to reset my password if I forget it',
    storyPoints: 5,
    priority: 'high',
    status: 'in_progress',
    assignedTo: '1',
    featureId: 'auth',
    sprintId: '2',
    projectId: '1',
    acceptanceCriteria: [
      'User can request password reset via email',
      'Reset link expires after 24 hours',
      'User can set new password',
    ],
    aiInsights: {
      complexity: 'medium',
      estimatedHours: 6,
      risk: 'low',
      recommendations: ['Use secure token generation', 'Send email notifications'],
    },
    createdAt: '2024-11-18T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
  },
  {
    id: '5',
    title: 'Dashboard Overview',
    description: 'As a user, I want to see an overview of my projects and tasks on the dashboard',
    storyPoints: 8,
    priority: 'high',
    status: 'todo',
    assignedTo: '2',
    featureId: 'dashboard',
    sprintId: '3',
    projectId: '1',
    acceptanceCriteria: [
      'Dashboard shows project statistics',
      'Recent activities are displayed',
      'Quick actions are available',
    ],
    aiInsights: {
      complexity: 'medium',
      estimatedHours: 10,
      risk: 'low',
      recommendations: ['Use charts for visual representation', 'Make it responsive'],
    },
    createdAt: '2024-11-20T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
  },
  {
    id: '6',
    title: 'Kanban Board',
    description: 'As a team member, I want to use a Kanban board to manage tasks',
    storyPoints: 13,
    priority: 'high',
    status: 'todo',
    assignedTo: '3',
    featureId: 'kanban',
    sprintId: '3',
    projectId: '1',
    acceptanceCriteria: [
      'Tasks can be dragged between columns',
      'Board is filterable by assignee and status',
      'Real-time updates are shown',
    ],
    aiInsights: {
      complexity: 'high',
      estimatedHours: 16,
      risk: 'medium',
      recommendations: ['Use react-beautiful-dnd', 'Implement optimistic updates'],
    },
    createdAt: '2024-11-20T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
  },
]

